# Generated by Django 5.0.3 on 2025-02-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystem', '0003_alter_early_withdrawal_note_alter_public_info_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='early_withdrawal',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='public_info',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
