# Generated by Django 5.0.3 on 2025-02-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystem', '0002_alter_early_withdrawal_note_alter_public_info_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='early_withdrawal',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='public_info',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
