# Generated by Django 5.0.3 on 2025-02-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='early_withdrawal',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('step1_option', models.IntegerField()),
                ('drop_course1', models.CharField(max_length=15)),
                ('drop_course2', models.CharField(max_length=15)),
                ('drop_course3', models.CharField(max_length=15)),
                ('departure_date', models.DateField()),
                ('step2_option', models.IntegerField()),
                ('step3_option', models.IntegerField()),
                ('return_date', models.DateField()),
                ('step4_option1', models.IntegerField()),
                ('step4_option2', models.IntegerField()),
                ('step4_option3', models.IntegerField()),
                ('step5_option1', models.IntegerField()),
                ('step5_option2', models.IntegerField()),
                ('step5_option3', models.IntegerField()),
                ('step5_option4', models.IntegerField()),
                ('step5_option5', models.IntegerField()),
                ('ID', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('returned', 'Returned'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('note', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Public_info',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=1)),
                ('ID', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('returned', 'Returned'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('note', models.CharField(max_length=255)),
            ],
        ),
    ]
