# Generated by Django 5.0.3 on 2025-03-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystem', '0007_alter_early_withdrawal_drop_course1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='early_withdrawal',
            name='step1_option',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='early_withdrawal',
            name='step2_option',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='early_withdrawal',
            name='step3_option',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='early_withdrawal',
            name='step4_option1',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='early_withdrawal',
            name='step4_option2',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='early_withdrawal',
            name='step4_option3',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='early_withdrawal',
            name='step5_option1',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='early_withdrawal',
            name='step5_option2',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='early_withdrawal',
            name='step5_option3',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='early_withdrawal',
            name='step5_option4',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='early_withdrawal',
            name='step5_option5',
            field=models.CharField(max_length=1),
        ),
    ]
