version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command:
      - sh
      - -c
      - |
        echo 'Waiting for MySQL...';
        while ! mysqladmin ping -h db -P 3306 --silent; do
          sleep 1;
        done;
        echo 'MySQL is ready!';
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000

    #command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

volumes:
  db_data:
