# Generated by Django 5.0.12 on 2025-02-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=45)),
                ("email", models.CharField(max_length=45)),
                ("role", models.CharField(default="basicuser", max_length=45)),
                ("status", models.CharField(max_length=1)),
            ],
        ),
    ]
