# Generated by Django 5.0.12 on 2025-02-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserManagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="token",
            field=models.CharField(default="", max_length=45),
        ),
    ]
