# Generated by Django 5.0.12 on 2025-02-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserManagement", "0002_users_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
