# Generated by Django 5.0.12 on 2025-02-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserManagement", "0003_alter_users_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="id",
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.CharField(
                max_length=45, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
