# Generated by Django 5.0.12 on 2025-02-09 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserManagement", "0004_remove_users_id_alter_users_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="user",
            new_name="name",
        ),
    ]
