# Generated by Django 5.0.3 on 2025-04-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level1',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='level2',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
