# Generated by Django 5.0.3 on 2025-04-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_user_level1_user_level2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cougarID',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
