# Generated by Django 5.0.3 on 2025-04-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0006_delegate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('form_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Level', models.CharField(default='2', max_length=1)),
            ],
        ),
    ]
