# Generated by Django 5.0.3 on 2025-03-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystem', '0006_alter_early_withdrawal_date_alter_public_info_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='early_withdrawal',
            name='drop_course1',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='early_withdrawal',
            name='drop_course2',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='early_withdrawal',
            name='drop_course3',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='early_withdrawal',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
