# Generated by Django 5.0.3 on 2025-03-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystem', '0008_alter_early_withdrawal_step1_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='early_withdrawal',
            name='step4_option1',
        ),
        migrations.RemoveField(
            model_name='early_withdrawal',
            name='step4_option2',
        ),
        migrations.RemoveField(
            model_name='early_withdrawal',
            name='step4_option3',
        ),
        migrations.RemoveField(
            model_name='early_withdrawal',
            name='step5_option1',
        ),
        migrations.RemoveField(
            model_name='early_withdrawal',
            name='step5_option2',
        ),
        migrations.RemoveField(
            model_name='early_withdrawal',
            name='step5_option3',
        ),
        migrations.RemoveField(
            model_name='early_withdrawal',
            name='step5_option4',
        ),
        migrations.RemoveField(
            model_name='early_withdrawal',
            name='step5_option5',
        ),
    ]
