# Generated by Django 5.0.3 on 2025-02-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='early_withdrawal',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='public_info',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
    ]
