# Generated by Django 5.0.3 on 2025-04-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystem', '0009_remove_early_withdrawal_step4_option1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='early_withdrawal',
            name='level1',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='early_withdrawal',
            name='level2',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='public_info',
            name='level1',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='public_info',
            name='level2',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
