# Generated by Django 5.0.3 on 2025-04-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystem', '0010_early_withdrawal_level1_early_withdrawal_level2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate_petition',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('level1', models.CharField(default='0', max_length=1)),
                ('level2', models.CharField(default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Undergraduate_transfer',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('level1', models.CharField(default='0', max_length=1)),
                ('level2', models.CharField(default='0', max_length=1)),
            ],
        ),
    ]
