# Generated by Django 5.0.3 on 2025-04-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApprovalSystem', '0012_historical_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_approval',
            name='locatedFolder',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
